### ISSUE TITLE
QA- code logic related. 

### ISSUE THREAD

**Issue by rocknswimmer** [Front-End-Retail/Atelier-Front-End#137]
https://github.com/Front-End-Retail/Atelier-Front-End/blob/0ebb5514c8e42355f35e082a9055a92ccf2eda63/client/src/QuestionsAndAnswers/Modal.js#L1-L17

looks like a test modal made to use to test a basic modal before creating the ones that would be used. should be an easy clean up.

**Comment by phodye** [comment]
I appreciate you pointing this out
