### ISSUE TITLE
QA-code logic

### ISSUE THREAD

**Issue by rocknswimmer** [Front-End-Retail/Atelier-Front-End#140]
https://github.com/Front-End-Retail/Atelier-Front-End/blob/0ebb5514c8e42355f35e082a9055a92ccf2eda63/client/src/QuestionsAndAnswers/QAAnswerSubmitForm.js#L39-L60

learned when Gabe showed me his form that this functionality is built into forms already. Not sure if this is easier than figuring out how to prevent refresh on submit. I did something similar in my code too since I did not know.

**Comment by phodye** [comment]
Thanks for your input!
